export const USER_MENU_ACTIONS = {
  SIGNIN: 'USER_MENU_SIGNIN',
  SIGNUP: 'USER_MENU_SIGNUP',
  PROFILE: 'USER_MENU_PROFILE',
  SETTINGS: 'USER_MENU_SETTINGS',
  LOGOUT: 'USER_MENU_LOGOUT',

};

export default null;
