export const loading = (type = '') => `${type}_LOADING`;
export const success = (type = '') => `${type}_SUCCESS`;
export const error = (type = '') => `${type}_ERROR`;

export const APP = {
  LOAD: 'APP_LOAD',
  TOGGLE_POPUP: 'APP_TOGGLE_POPUP',
  DO_SIGNUP: 'APP_DO_SIGNUP',
  DO_LOGIN: 'APP_DO_LOGIN',
  DO_UPDATE_USER: 'APP_DO_UPDATE_USER',
  DO_FACEBOOK_LOGIN: 'APP_DO_FACEBOOK_LOGIN',
  DO_DISCONNECT_FACEBOOK: 'APP_DISCONNECT_FACEBOOK',
  DO_RESET_PWD: 'APP_DO_RESET_PWD',
  DO_LOGOUT: 'APP_DO_LOGOUT',
  CLEAR_ERROR: 'APP_CLEAR_ERROR',
};

export const GAMER_DETAILS = {
  LOAD: 'GAMER_DETAILS_LOAD',
  APPLY_REVIEW_FILTERS: 'GAMER_DETAILS_APPLY_REVIEW_FILTERS',
};

export const NOTIFICATIONS = {
  PUSH: 'NOTIFICATIONS_PUSH',
  DELETE: 'NOTIFICATIONS_DELETE',
};
